{ pkgs, ... }:
{
    home.packages = with pkgs; [
        ripgrep 
        fd
        fzf
        eza
        bat
        tree
        htop
        jq
        curl
        wget
        neofetch
        fastfetch
        zoxide
        sesh
        thefuck
        nodejs
        python3
        cargo
        wofi
        nautilus
        discord
        xdg-desktop-portal
        xdg-desktop-portal-wlr
        xdg-desktop-portal-gtk
        docker-compose
        lazydocker
        docker-buildx
        spotify
        zig
        unzip
        clang-tools
        man-pages
    ];
}
